#!/usr/bin/env bash

GETH_VERSION=v1.8.3

call_geth() {
    docker run \
        --name 'geth-private' \
        -it \
        --rm \
        -v ~/data/ethereum:/root \
        -v $PWD:/cwd \
        -p 8545:8545 \
        ethereum/client-go:$GETH_VERSION --config /cwd/config-$GETH_VERSION.toml \
        $@
}

call_geth $@
