#!/usr/bin/env python

import sys

print '// THIS FILE IS GENERATED BY %s. DONT EDIT.\n' % sys.argv[0]
print '#ifndef TOWNCRIER_TRUSTED_CERTS_H'
print '#define TOWNCRIER_TRUSTED_CERTS_H'

print '#define TRUSTED_CERTS \\'
for l in sys.stdin:
    print r'"' + l.strip() + "\\r\\n\"\\"

print '""'

print '#endif'
