#!/usr/bin/env python

import sys

print '// THIS FILE IS GENERATED BY %s. DONT EDIT.\n' % sys.argv[0]
print '#ifndef TOWNCRIER_TRUSTED_CERTS_H'
print '#define TOWNCRIER_TRUSTED_CERTS_H'
print ''
print '#define mozilla_ca_bundle \\'
with open(sys.argv[1], 'r') as infile:
    for l in infile.readlines():
        print r'"' + l.strip() + "\\r\\n\"\\"

print ""
print '#endif'
