#!/bin/bash

GETH_VERSION=v1.8.3
DOCKER_FLAGS="-it --rm"

while getopts ":dv:" opt; do
    case ${opt} in
        d)
            DOCKER_FLAGS+=" -d"
            ;;
        v)
            GETH_VERSION=$OPTARG
            ;;
        \?)
            echo "Invalid Option: -$OPTARG";
            exit 1
            ;;
    esac
done

docker run \
	--name 'geth-rink' \
	${DOCKER_FLAGS} \
	--rm \
	-v /data/ethereum/rinkeby:/root \
	-v $PWD/rinkeby.json:/genesis.json \
	-v $PWD/config-${GETH_VERSION}.toml:/config.toml \
        -p 8545:8545 \
        -p 30303:30303 \
	ethereum/client-go:${GETH_VERSION} $@

