#!/bin/bash

geth --testnet \
     --fast \
     --port 30000 \
     --rpc \
     --rpcapi "db,eth,ne,web3,personal,crypto-js" \
     --rpcaddr 127.0.0.1\
     --rpcport 8200\
     --rpccorsdomain '*' \
     --ipcdisable \
     --verbosity 3 \
     --keystore "wallet" \
     $@
