#include <gtest/gtest.h>

#include "utils.h"
#include "Enclave_u.h"
#include "key-utils.h"

class TransactionSuiteTest : public ::testing::Test {
 protected:
  sgx_enclave_id_t eid;
  virtual void SetUp() {
    initialize_enclave(ENCLAVE_FILENAME, &eid);
  }

  virtual void TearDown() {
    sgx_destroy_enclave(eid);
  }
};

TEST_F(TransactionSuiteTest, All) {
  int ret;
#define SEALED_KEY "BAACAAAAAABIIPM3auay8gNNO3pLSKd4y/////////8AAAAAAAAAAMmTv7tkyuQ34fpQ5VRNOjwHX7dBwsi8VdLR3IB4FljF/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAANURSkg1WgSuijoRD8ziZfVA27eypCN2RKglKGjY9vPDz636xSK/N2K9M8oyYySNGmBloTT+fwAAoGShNP5/AAAAMIDdAAAAAAAAAAAAAAAAAAAAAAAAAADYzYHdoX8AAEBgoTT+fwAAQFVY3KF/AACQZKE0/n8AADONTAAAAAAAqGShNP5/AAAt4yDcoX8AAAYAAAAAAAAAkBCA3aF/AAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAACAyoHdoX8AAAAAAAAAAAAAawQAAAAAAACAyoHdoX8AAAAAAAAAAAAA2M2B3aF/AACwX6E0/n8AAGsEAAABAAAAoF+hNP5/AABxBiCYAAAAALfdFd2hfwAA/////wAAAAAgAAAAAAAAAHige9yhfwAAADCA3aF/AADogkAAAAAAADhgoTT+fwAAmYRYXAAAAAASYnEBAAAAABkAAAAAAAAARBxg3QIAAAAw+RTdoX8AAHcEAAAAAAAA4DmA3aF/AABEHGDdoX8AAPgfHdyhfwAABAEAAAAAAAAQRYDdoX8AABhv0tyhfwAA+I7S3KF/AAB7JGDdoX8AAAQBAAAAAAAA+I7S3KF/AAAQRYDdoX8AAPhgoTT+fwAA9GChNP5/AABEHGDdoX8AAA=="

  provision_key(eid, SEALED_KEY);
  transaction_rlp_test(eid, &ret);
  EXPECT_EQ(0, ret);
}
